language: php

php:
  - 5.5
  - 5.6
  - hhvm

env:
  - DB=mysql

before_script:
  - mv travis.env.php .env.testing.php
  - mysql -e 'create database IF NOT EXISTS spartapark;'
  - travis_retry composer self-update
  - travis_retry composer install --prefer-source --no-interaction --dev
  - chmod -R 777 app/storage

script: vendor/bin/phpunit --stderr

matrix:
  allow_failures:
    - php: hhvm
  fast_finish: true